/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package test.thostmduserapi;

public class CThostFtdcExchangeQuoteField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcExchangeQuoteField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcExchangeQuoteField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        thostmduserapiJNI.delete_CThostFtdcExchangeQuoteField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAskPrice(double value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskPrice_set(swigCPtr, this, value);
  }

  public double getAskPrice() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskPrice_get(swigCPtr, this);
  }

  public void setBidPrice(double value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidPrice_set(swigCPtr, this, value);
  }

  public double getBidPrice() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidPrice_get(swigCPtr, this);
  }

  public void setAskVolume(int value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskVolume_set(swigCPtr, this, value);
  }

  public int getAskVolume() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskVolume_get(swigCPtr, this);
  }

  public void setBidVolume(int value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidVolume_set(swigCPtr, this, value);
  }

  public int getBidVolume() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidVolume_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_RequestID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_BusinessUnit_get(swigCPtr, this);
  }

  public void setAskOffsetFlag(char value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskOffsetFlag_set(swigCPtr, this, value);
  }

  public char getAskOffsetFlag() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskOffsetFlag_get(swigCPtr, this);
  }

  public void setBidOffsetFlag(char value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidOffsetFlag_set(swigCPtr, this, value);
  }

  public char getBidOffsetFlag() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidOffsetFlag_get(swigCPtr, this);
  }

  public void setAskHedgeFlag(char value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskHedgeFlag_set(swigCPtr, this, value);
  }

  public char getAskHedgeFlag() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskHedgeFlag_get(swigCPtr, this);
  }

  public void setBidHedgeFlag(char value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidHedgeFlag_set(swigCPtr, this, value);
  }

  public char getBidHedgeFlag() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidHedgeFlag_get(swigCPtr, this);
  }

  public void setQuoteLocalID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_QuoteLocalID_set(swigCPtr, this, value);
  }

  public String getQuoteLocalID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_QuoteLocalID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_ClientID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_InstallID_get(swigCPtr, this);
  }

  public void setNotifySequence(int value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_NotifySequence_set(swigCPtr, this, value);
  }

  public int getNotifySequence() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_NotifySequence_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_SettlementID_get(swigCPtr, this);
  }

  public void setQuoteSysID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_QuoteSysID_set(swigCPtr, this, value);
  }

  public String getQuoteSysID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_QuoteSysID_get(swigCPtr, this);
  }

  public void setInsertDate(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_InsertDate_set(swigCPtr, this, value);
  }

  public String getInsertDate() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_InsertDate_get(swigCPtr, this);
  }

  public void setInsertTime(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_InsertTime_set(swigCPtr, this, value);
  }

  public String getInsertTime() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_InsertTime_get(swigCPtr, this);
  }

  public void setCancelTime(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_CancelTime_set(swigCPtr, this, value);
  }

  public String getCancelTime() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_CancelTime_get(swigCPtr, this);
  }

  public void setQuoteStatus(char value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_QuoteStatus_set(swigCPtr, this, value);
  }

  public char getQuoteStatus() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_QuoteStatus_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_ClearingPartID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_SequenceNo_get(swigCPtr, this);
  }

  public void setAskOrderSysID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskOrderSysID_set(swigCPtr, this, value);
  }

  public String getAskOrderSysID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_AskOrderSysID_get(swigCPtr, this);
  }

  public void setBidOrderSysID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidOrderSysID_set(swigCPtr, this, value);
  }

  public String getBidOrderSysID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_BidOrderSysID_get(swigCPtr, this);
  }

  public void setForQuoteSysID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_ForQuoteSysID_set(swigCPtr, this, value);
  }

  public String getForQuoteSysID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_ForQuoteSysID_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_BranchID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    thostmduserapiJNI.CThostFtdcExchangeQuoteField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return thostmduserapiJNI.CThostFtdcExchangeQuoteField_MacAddress_get(swigCPtr, this);
  }

  public CThostFtdcExchangeQuoteField() {
    this(thostmduserapiJNI.new_CThostFtdcExchangeQuoteField(), true);
  }

}
